import { Link } from "wouter";
import { ArrowUpRight, BrainCircuit, Check, FolderKanban, ListTodo, MessageSquare, Search, Sparkles, Target, Zap } from "lucide-react";

const features = [
  { icon: BrainCircuit, title: "IA para produtividade", text: "Converse com uma IA real para pensar, escrever e decidir com mais clareza." },
  { icon: FolderKanban, title: "Projetos com contexto", text: "Dê instruções próprias para cada frente de trabalho e mantenha tudo no lugar." },
  { icon: Target, title: "Estudos que avançam", text: "Explique, resuma e transforme conteúdo em próximos passos de aprendizagem." },
  { icon: ListTodo, title: "Tarefas acionáveis", text: "Tire ideias da conversa e organize o que precisa acontecer depois." },
  { icon: Search, title: "Histórico encontrável", text: "Busque conversas, mensagens, projetos e tarefas sem recomeçar do zero." },
  { icon: Zap, title: "Ritmo de trabalho", text: "Uma mesa de trabalho única para sair do pensamento disperso para a ação." },
];

const plans = [
  { code: "FREE", name: "Free", price: "R$ 0", note: "para começar com o essencial", items: ["30 conversas por mês", "2 projetos", "30 tarefas", "Assistentes de estudo e produtividade"], cta: "Começar agora", href: "/register" },
  { code: "PRO", name: "Pro", price: "R$ 39,90", note: "para quem quer ganhar ritmo", items: ["500 conversas por mês", "20 projetos e 500 tarefas", "Histórico ilimitado e busca", "Modelos avançados e exportação"], cta: "Assinar Pro", href: "https://mpago.la/14CRH6L" },
  { code: "BUSINESS", name: "Business", price: "R$ 99,90", note: "para operações mais intensas", items: ["2.000 conversas por mês", "Projetos e tarefas ilimitados", "Prioridade máxima", "Recursos empresariais"], cta: "Assinar Business", href: "https://mpago.la/2dbzEGa" },
];

export default function Home() {
  return <div className="landing">
    <header className="landing-header"><Link href="/"><div className="brand-lockup"><span className="brand-mark"><i /><b /></span><span className="brand-name">Produtiva<span>AI</span></span></div></Link><nav className="landing-nav"><a href="#recursos">Recursos</a><a href="#planos">Planos</a><Link href="/login">Entrar</Link></nav><Link href="/register" className="button button-dark button-small">Começar agora <ArrowUpRight size={15} /></Link></header>
    <main>
      <section className="hero-section"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14} /> INTELIGÊNCIA PARA O SEU RITMO</p><h1>Dê forma à próxima coisa <em>importante.</em></h1><p className="hero-lede">ProdutivaAI é sua central de inteligência para transformar pensamento disperso em trabalho que avança — com contexto, projetos e próximos passos no mesmo lugar.</p><div className="hero-actions"><Link href="/register" className="button button-lime">Começar agora <ArrowUpRight size={17} /></Link><a href="#recursos" className="text-link">Veja como funciona <span>↓</span></a></div><div className="hero-meta"><span><i className="status-dot" /> IA real, sem respostas pré-programadas</span><span>Feito para estudo e trabalho</span></div></div><div className="hero-visual"><div className="visual-grid" /><div className="signal-card signal-card-main"><div className="signal-header"><span className="signal-pulse" /> sessão em foco <span className="mono">09:42</span></div><div className="signal-line signal-line-long" /><div className="signal-line signal-line-mid" /><div className="signal-line signal-line-short" /><div className="signal-footer"><span>próximo passo</span><strong>organizar e agir</strong><ArrowUpRight size={17} /></div></div><div className="signal-card signal-card-float"><span className="mono">01</span><strong>clareza</strong><span>antes de velocidade</span></div><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /></div></section>
      <section className="trust-strip"><span>uma mesa para pensar</span><span>um contexto para continuar</span><span>um sistema para avançar</span></section>
      <section id="recursos" className="section-block"><div className="section-heading"><p className="eyebrow">O QUE MUDA</p><h2>Menos troca de contexto.<br /><em>Mais trabalho concluído.</em></h2><p>O ProdutivaAI junta conversa, projeto e execução em uma experiência direta, sem ruído desnecessário.</p></div><div className="feature-grid">{features.map(feature => { const Icon = feature.icon; return <article className="feature-card" key={feature.title}><div className="feature-icon"><Icon size={20} /></div><h3>{feature.title}</h3><p>{feature.text}</p><span className="card-arrow">↗</span></article>; })}</div></section>
      <section id="planos" className="section-block plans-section"><div className="section-heading section-heading-inline"><div><p className="eyebrow">PLANOS SIMPLES</p><h2>Escolha o seu espaço<br /><em>para fazer mais.</em></h2></div><p>Comece no seu ritmo. A troca de plano só acontece após confirmação real do pagamento pelo Mercado Pago.</p></div><div className="plans-grid">{plans.map(plan => <article className={`plan-card ${plan.code === "PRO" ? "plan-featured" : ""}`} key={plan.code}>{plan.code === "PRO" && <span className="plan-badge">MAIS ESCOLHIDO</span>}<div className="plan-top"><span className="plan-name">{plan.name}</span><span className="plan-price">{plan.price}<small>/mês</small></span><span className="plan-note">{plan.note}</span></div><ul>{plan.items.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul>{plan.href.startsWith("http") ? <a className={`button ${plan.code === "PRO" ? "button-lime" : "button-outline"} button-full`} href={plan.href} target="_blank" rel="noreferrer">{plan.cta}<ArrowUpRight size={16} /></a> : <Link className={`button ${plan.code === "PRO" ? "button-lime" : "button-outline"} button-full`} href={plan.href}>{plan.cta}<ArrowUpRight size={16} /></Link>}</article>)}</div></section>
      <section className="closing-section"><div><p className="eyebrow">O PRÓXIMO PASSO É SEU</p><h2>Seu trabalho continua<br /><em>de onde você parou.</em></h2></div><Link href="/register" className="button button-lime">Criar minha conta <ArrowUpRight size={17} /></Link></section>
    </main><footer className="landing-footer"><div className="brand-lockup"><span className="brand-mark"><i /><b /></span><span className="brand-name">Produtiva<span>AI</span></span></div><span>Sua inteligência artificial para fazer mais.</span><span>© {new Date().getFullYear()} ProdutivaAI</span></footer>
  </div>;
}
